trigger: none 

pool: 
  vmImage: 'ubuntu-latest'
  
steps:
  - script: echo Hello, world!
    displayName: 'Test line'

  - task: PythonScript@0
    inputs:
      scriptSource: 'inline'
      script: 'print "this is a test %%%%%%%%%%%%%%%'''